auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: zorrock.com
url: http://zorrock.github.io
feed: /atom.xml
author_info: <a href="http://zorrock.github.io/">BeiYuu</a>
